### ISSUE TITLE
Poll 80 Changes

### ISSUE THREAD

**Issue by NicholasGFX** [adnapPanda/pyramid-plunder-counter#10]
Sceptre rolls now regardless of if an NPC spawns as of the Poll 80 changes listed [here](https://secure.runescape.com/m=news/poll-80-toa-changes--dmm-tweaks?oldschool=1) 

Plugin currently shows inaccurate counts based on failed rolls. All rolls should be successful now.

**Comment by adnapPanda** [comment]
It has already been updated with the new rates and tracks the rolls regardless of npc spawns.
