### ISSUE TITLE
counter

### ISSUE THREAD

**Issue by Kas3m** [adnapPanda/pyramid-plunder-counter#2]
Hello I know this is supposed to only count the successfuly looted chests but can't we make it count every chest please even the one that spawns swarms its easier to track the total progress?
thanks for the great effort and the great plugin

**Comment by adnapPanda** [comment]
Implemented in PR: https://github.com/runelite/plugin-hub/pull/3530

**Comment by Kas3m** [comment]
thank you so much I really apprecaite all the efforts to make this accept my respect sir
