### ISSUE TITLE
Feature request: Chest counter per room

### ISSUE THREAD

**Issue by Raisoshi** [adnapPanda/pyramid-plunder-counter#3]
It would be nice to be able to use the plugin to figure out how dry you are for the sceptre, but considering each room has a different drop rate, a universal chests opened counter will only help if you're doing like, last chest only runs.

An even better thing would be to have a % counter with "Chance to receive at least one scepter" by the amount of chests opened, this is a bit more complicated as the formula will have to take into account the different drop rates but with a basic understanding of statistics shouldn't be too bad to figure out I'm guessing? I could make a spreadsheet myself if I got the first paragraph suggestion though so that would be enough if this is too difficult.

**Comment by adnapPanda** [comment]
Thanks for the suggestion. I will have a look into your second idea with the % counter.

**Comment by adnapPanda** [comment]
Closed with commit fed7c79fa152ef74a13b9139659702186c41c79b

**Comment by Raisoshi** [comment]
That was quick, this is awesome thank you!! It just updated in real time for me right now in the middle of a plunder haha

**Comment by adnapPanda** [comment]
Always happy for new feature requests/bug reports. :)
