### ISSUE TITLE
Feature-Request: Cross-Session counter

### ISSUE THREAD

**Issue by Auristite** [adnapPanda/pyramid-plunder-counter#5]
Personally, I've had multiple sessions where I've not obtained the sceptre and would have loved to track the total chests and sarcophagi opened until I receive the sceptre, however with it resetting when I exit RuneLite I no longer get to see the previous information.

A way to add this feature could be to store the data in a specific class and to export the necessary data (total chests, total sarcophagi, successful chests, successful sarcophagi and total chance) to a JSON file when the player leaves the area of the Pyramid or the plugin shuts down and then to re-import the data when the plugin starts up or they re-enter the pyramid; I've already very crudely and quickly recreated the plugin and tested the concept to see that it would work.

**Comment by adnapPanda** [comment]
if you have already implemented this it might be faster to make a pull request to this repo. I probably won't have time to implement this feature this week.

**Comment by adnapPanda** [comment]
Had to make a minor change to inject the Gson, but the PR is now open to runelite. Thanks
https://github.com/runelite/plugin-hub/pull/4149
