### ISSUE TITLE
Game Update - Rates and Sarcophagi Changed

### ISSUE THREAD

**Issue by PJGJ210** [adnapPanda/pyramid-plunder-counter#7]
I think the rates are the same (change is in backend to correct their math) but the Sarcophagi now does not matter if it is success or failure.

![image](https://github.com/adnapPanda/pyramid-plunder-counter/assets/16944807/a263fa34-a472-4efa-8d35-1a76764c7bb4)

**Comment by adnapPanda** [comment]
Yea, good point. This makes the calculations so much easier since I dont have to worry about failure anymore. Will update this weekend

**Comment by adnapPanda** [comment]
closed with commit 0e0a206187e5df1f8ddb089cbbf8917174891f57

**Comment by adnapPanda** [comment]
Pull request has been created for plugin hub
https://github.com/runelite/plugin-hub/pull/4834
